Bar-Spot-Capstone/bar-spot

- server/.gitignore
- server/package-lock.json
- server/package.json
- server/src/config/connection.ts
- server/src/index.ts
Initiated data base instance, created connection file and synced data base to server.
> BS-8-Set-up-and-sync-data-base

- server/package-lock.json
- server/package.json
- server/src/models/Users.ts
- server/tsconfig.json
Created a user table with a unique name and email, along with a password.
> BS-10-Created-user-table

- server/jest.config.js
- server/package-lock.json
- server/package.json
- server/src/controllers/User.ts
- server/src/index.ts
- server/src/routes/User.ts
- server/src/test/user.test.ts
Added a new endpoint: http://localhost:3000/user/register with an appropriate body to submit a request for a new user to be registered in the database. I also added and set up test cases using the Jest test. Next steps are to set up a git workflow for automation testing on pull requests and push.
> BS-11-User-register

- .github/workflows/server-test.yml
- README.md
Created yml file for github actions automation
> BS-12-Test-automation

- server/src/models/Favorite.ts
- server/src/models/Users.ts
Created the Favorite table which belongs to the User table.
> BS-9-Created-favorite-table

- server/src/controllers/User.ts
- server/src/routes/User.ts
- server/src/test/user.test.ts
Login endpoint that takes in the email and password as args within the body of the request and returns the user_id, username, and email.
> BS-15-Login-endpoint

- server/src/controllers/Group.ts
- server/src/controllers/User.ts
- server/src/index.ts
- server/src/routes/Group.ts
- server/src/test/group.test.ts
- server/src/test/user.test.ts
Implemented a endpoint for group table to add new entry with the column and body of the request being the group name
> BS-18-Create-group-endpoint

- server/src/models/Group.ts
- server/src/models/UserGroup.ts
- server/src/models/Users.ts
Established a join table for user and group table to link a user and a group together for party system. The new table also store the role of each user.
> BS-25-Established-user-group-table

- README.md
Edited readme with instructions on how to set up project
> Edited-readme

- server/package-lock.json
- server/package.json
- server/src/index.ts
Established cors to listen out for request on port 3000, requiring credentials.
> Establish-cors

- server/src/controllers/UserGroup.ts
- server/src/routes/UserGroup.ts
- server/src/test/usergroup.test.ts
Established delete REST methods for UserGroup party system
- Owner of the party is able to delete the party
- Members are able to leave the party, owners cannot leave unless there no other members in the party
> BS-29-Delete-party

- server/src/controllers/User.ts
- server/src/routes/User.ts
- server/src/test/user.test.ts
Established delete method for the user model that will delete a user based on there id
- Id is fetched from the parameter of the url
- Program checks if user is in a group
- If a user is in a group, it prevents the user from deleting themselves if there the owner
- If the user is not in a group, the user is deleted from the data base
> BS-30-Delete-user

- server/src/controllers/Favorites.ts
- server/src/models/Favorites.ts
- server/src/models/Users.ts
- server/src/routes/Favorites.ts
- server/src/test/favorites.test.ts
Allows for getting a user favorites and added test cases.
> BS-13-Get-favorite-table

- server/src/controllers/User.ts
- server/src/test/user.test.ts
Edited the response for pre-existing user
> BS-35-Edited-error-response

- frontend/src/components/Group.tsx
- frontend/src/components/NavBar.tsx
- frontend/src/styles/NavBar.css
- server/src/controllers/User.ts
- server/src/controllers/UserGroup.ts
- server/src/routes/User.ts
- server/src/test/user.test.ts
- server/src/test/usergroup.test.ts
Created a responsive group creation and invitation design
Group creation allows users to
- Have unique group name
- View all users
- Send invites to other users
- Create group
Group invitation displays
- Number of invitations 
- Group name and group owner username
- Confirmation tab to confirm or decline invitation 
Next steps,
- Redesign group database structure to not instantly add a user to the usergroup when a invitation is sent
- Create a invitation system & table that stores the invitations a user has
> BS-41-Group-&-invite-UI

- server/src/controllers/Invitations.ts
- server/src/controllers/UserGroup.ts
- server/src/index.ts
- server/src/models/Invitations.ts
- server/src/routes/Invitations.ts
- server/src/routes/UserGroup.ts
- server/src/test/invitation.test.ts
- server/src/test/usergroup.test.ts
In response to the need for a more resilient and versatile group system, this pull request introduces an enhanced database schema. This schema overhaul facilitates the transition to an invitation-based group system, which offers improved flexibility and security.
Changes Implemented:
New Database Schema: Designed and implemented a comprehensive database schema tailored to support the invitation-based group system. This schema lays the foundation for robust group management and user interactions.
Invitation-Based Group System: Transitioned the existing group system to operate on an invitation-based model. This approach enhances user control and facilitates seamless collaboration within groups.
> BS-44-Group-system-revamp

- frontend/src/components/Group.tsx
- frontend/src/components/NavBar.tsx
- frontend/src/state/slices/groupSlice.ts
- frontend/src/state/slices/userSlice.ts
- frontend/src/state/store.ts
- frontend/src/types/types.ts
- server/src/controllers/UserGroup.ts
- server/src/routes/UserGroup.ts
- server/src/test/usergroup.test.ts
Implemented and integrated group system; 
- Users can create a group and invite other users
- Users can accept or decline invites
- Users group information will be retrieved on login
> BS-45-Group-endpoint-integration

- frontend/package-lock.json
- frontend/package.json
Added packages and scripts for git hub pages deployment.
Installed packages from: npm install gh-pages --save-dev
> BS-48-Git-pages-packages-and-scripts

- .github/workflows/deploy.yml
- .github/workflows/server-test.yml
- frontend/package.json
- frontend/vite.config.ts
Edited build script to accommodate for vite
> BS-48-Script-for-build

- .github/workflows/deploy.yml
Upgraded to node 16 and changed target file path
> BS-Actions-patch-1

- .github/workflows/deploy.yml
> BS-Action-Patch-2

- .github/workflows/deploy.yml
- .github/workflows/server-test.yml
- frontend/package-lock.json
- frontend/package.json
- frontend/vite.config.ts
Packages and scripts that are needed to deploy the front-end.
These packages must be merged with the main branch in order to deploy the website correctly. Deploying from a separate branch will not work as per GitHub's instructions.
> BS-Prod-packages

- frontend/package.json
- frontend/vite.config.ts
Changed base url to be 
base: "/bar-spot/frontend/"
> BS-48-Changed-base-url

- frontend/vite.config.ts
> BS-48-Changed-base

- frontend/vite.config.ts
> BS-48-Revert-base-change

- frontend/src/main.tsx
Updated router paths to reflect;
/bar-spot/frontend/
> BS-48-Adjusted-router-paths

- frontend/src/main.tsx
Reverted + added slash to login -> /login
> BS-48-Reverted-and-added-slash-to-login

- frontend/src/main.tsx
> BS-48-Changed-base-name

- frontend/src/main.tsx
Changed router to reflect /bar-spot/
> BS-48-Changed-router

- frontend/src/components/Group.tsx
- frontend/src/components/NavBar.tsx
- frontend/src/pages/CreateNewAcc.tsx
- frontend/src/pages/Login.tsx
- frontend/src/pages/MapView.tsx
- frontend/src/pages/Profile.tsx
- frontend/src/types/fetchCall.tsx
Added a default file to store routes 
Changed all routes to fetch from deployed render server
> BS-48-Fetchs-now-call-from-deployed-server

- frontend/package-lock.json
- frontend/src/components/CardInfo.tsx
- frontend/src/components/MoreInfo.tsx
- frontend/src/components/QuickInfo.tsx
- frontend/src/pages/MapView.tsx
- frontend/src/styles/MapView.css
- frontend/src/types/types.ts
- server/package-lock.json
Updated UI for map view
Added new sorting feature based on 
- distance from the user
- 5 star rating of the location
- name of the bar
Map now responds to user input by centering on the bar they chose 
More info button now works 
Better fragmented code into reusable components
> B3-43-info-UI-and-bar-sorting

- frontend/src/components/Group.tsx
- frontend/src/components/NavBar.tsx
- frontend/src/pages/Login.tsx
- frontend/src/pages/Profile.tsx
- server/package-lock.json
- server/package.json
- server/src/controllers/User.ts
- server/src/index.ts
- server/src/routes/Favorites.ts
- server/src/routes/Invitations.ts
- server/src/routes/User.ts
- server/src/routes/UserGroup.ts
- server/src/routes/Visited.ts
- server/src/test/user.test.ts
Establish JWT tokens on user login that persist and is sent to the client browser.
Form token the client will be able to decipher the user information and set the cookie in the header for allowing the user to hit other endpoints.
> BS-47-JWT-auth

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/NavBar.tsx
Established a model view for party activities. 
- Bar chaining activity with 2 sliders and a drop down option
- Bar hopping activity with 1 slider and a drop down option
> BS-52-Activities-UI

- frontend/src/components/NavBar.tsx
- frontend/src/state/slices/groupSlice.ts
- frontend/src/state/slices/userSlice.ts
Implemented log out button that;
- Clears the JWT token from the storage
- Rests the userState
- Rests the groupState
- Refreshes the page
> BS-54-Logout-button
